//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeClass
    {
        public int Id { get; set; }
        public string Category { get; set; }
        public Nullable<double> Experience { get; set; }
        public Nullable<int> Hours { get; set; }
    
        public virtual EmployeeData EmployeeData { get; set; }
    }
}
