//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
    
        public virtual EmployeeClass EmployeeClass { get; set; }
        public virtual LastMonth LastMonth { get; set; }
        public virtual Month Month { get; set; }
        public virtual NextMonth NextMonth { get; set; }
        public virtual Vacation Vacation { get; set; }
    }
}
